import time

from gemini import search_gemini

def gemini_paraphrase_data(company_profile,industry_type):
    industry_code = '119-Accounting / Auditing, 172-Advertising & Marketing, 180-Agriculture / Forestry / Fishing, 101-Analytics / KPO / Research, 173-Animation & VFX, 120-Architecture/Interior Design, 148-Auto Components, 149-Automobile, 162-Aviation, 102-BPO / Call Centre, 112-Banking, 135-Beauty & Personal Care, 136-Beverage, 128-Biotechnology, 150-Building Material, 151-Chemicals, 129-Clinical Research / Contract Research,137-Consumer Electronics & Appliances, 121-Content Development / Language, 163-Courier / Logistics, 152-Defence & Aerospace, 122-Design, 134- E-Learning / EdTech, 133-Education / Training, 153-Electrical Equipment, 103-Electronic Components / Semiconductors, 104- Electronics Manufacturing, 105- Emerging Technologies, 164- Engineering & Construction, 174- Events / Live Entertainment, 139-FMCG, 123-Facility Management Services, 154-Fertilizers / Pesticides / Agro chemicals, 175- Film / Music / Entertainment, 114- FinTech / Payments, 113- Financial Services, 138- Fitness & Wellness, 140- Food Processing, 141- Furniture & Furnishing, 176- Gaming, 142- Gems & Jewellery, 181- Government / Public Administration, 107- Hardware & Networking, 143- Hotels & Restaurants, 109- IT Services & Consulting, 182- Import & Export, 155- Industrial Automation, 156- Industrial Equipment / Machinery, 115- Insurance, 108- Internet, 116- Investment Banking / Venture Capital / Private Equity, 157- Iron & Steel, 124- Law Enforcement / Security Services, 144- Leather, 125- Legal, 126- Management Consulting, 130- Medical Devices & Equipment, 131- Medical Services / Hospital, 158- Metals & Mining, 183- Miscellaneous, 117- NBFC, 184- NGO / Social Services / Industry Associations, 165- Oil & Gas, 159- Packaging & Containers, 160- Petrochemical / Plastics / Rubber, 132- Pharmaceutical & Life Sciences, 166- Ports & Shipping, 167- Power, 177- Printing & Publishing, 161- Pulp & Paper, 168- Railways, 169- Real Estate, 127- Recruitment / Staffing, 145- Retail, 110- Software Product, 178- Sports / Leisure & Recreation, 179- TV / Radio, 111- Telecom / ISP, 146- Textile & Apparel, 147- Travel & Tourism, 170- Urban Transport, 171- Water Treatment / Waste Management'
    command=f'provide me rephrased company profile of the following description:"{company_profile}" in 40-50 words and also provide me the most accurate industry code from the list of industry code:{industry_code} and industry description:{industry_type} as reference'
    time.sleep(2)
    res=search_gemini(command)
    res=res['candidates'][0]['content']['parts'][0]['text']
    res=str(res)
    return res

def gemini_company_description(company_name,cs_link):
    industry_code = '119-Accounting / Auditing, 172-Advertising & Marketing, 180-Agriculture / Forestry / Fishing, 101-Analytics / KPO / Research, 173-Animation & VFX, 120-Architecture/Interior Design, 148-Auto Components, 149-Automobile, 162-Aviation, 102-BPO / Call Centre, 112-Banking, 135-Beauty & Personal Care, 136-Beverage, 128-Biotechnology, 150-Building Material, 151-Chemicals, 129-Clinical Research / Contract Research,137-Consumer Electronics & Appliances, 121-Content Development / Language, 163-Courier / Logistics, 152-Defence & Aerospace, 122-Design, 134- E-Learning / EdTech, 133-Education / Training, 153-Electrical Equipment, 103-Electronic Components / Semiconductors, 104- Electronics Manufacturing, 105- Emerging Technologies, 164- Engineering & Construction, 174- Events / Live Entertainment, 139-FMCG, 123-Facility Management Services, 154-Fertilizers / Pesticides / Agro chemicals, 175- Film / Music / Entertainment, 114- FinTech / Payments, 113- Financial Services, 138- Fitness & Wellness, 140- Food Processing, 141- Furniture & Furnishing, 176- Gaming, 142- Gems & Jewellery, 181- Government / Public Administration, 107- Hardware & Networking, 143- Hotels & Restaurants, 109- IT Services & Consulting, 182- Import & Export, 155- Industrial Automation, 156- Industrial Equipment / Machinery, 115- Insurance, 108- Internet, 116- Investment Banking / Venture Capital / Private Equity, 157- Iron & Steel, 124- Law Enforcement / Security Services, 144- Leather, 125- Legal, 126- Management Consulting, 130- Medical Devices & Equipment, 131- Medical Services / Hospital, 158- Metals & Mining, 183- Miscellaneous, 117- NBFC, 184- NGO / Social Services / Industry Associations, 165- Oil & Gas, 159- Packaging & Containers, 160- Petrochemical / Plastics / Rubber, 132- Pharmaceutical & Life Sciences, 166- Ports & Shipping, 167- Power, 177- Printing & Publishing, 161- Pulp & Paper, 168- Railways, 169- Real Estate, 127- Recruitment / Staffing, 145- Retail, 110- Software Product, 178- Sports / Leisure & Recreation, 179- TV / Radio, 111- Telecom / ISP, 146- Textile & Apparel, 147- Travel & Tourism, 170- Urban Transport, 171- Water Treatment / Waste Management'
    command=f"provide me the company profile in 50-60 words of a company {company_name}, and in separate provide me single code of industry type from ({industry_code}) keep career page url as reference {cs_link}"
    res=search_gemini(command)
    res=res['candidates'][0]['content']['parts'][0]['text']
    res=str(res)
    return res


#print(gemini_paraphrase_data('HBeonlabs','Industrial Automation'))

